182200137 - work1
west2-online-reserve/collection-golang pull request #1
Opened 2023-09-06 04:08 UTC by RukiaOvO

All the basic works and Bonus is done.
btw, I'm confused about the output-example of Q5 in Task1.
It requires to add 114514 to the end of slice while the output-example is 666.

2023-09-06 04:46 UTC, ozline commented on work1/Bonus4.go
看起来像是gpt的, 但是问题不大

2023-09-06 04:48 UTC, ozline commented on work1/Bonus2.md
乱码了, 改一下哈

2023-09-06 04:50 UTC, ozline requested changes
没啥大问题, 问题都在comment里面了, 还有一个就是

6.go这个文件名我没有太看明白, 或许可以改成Bonus1之类的

Bonus3给了2个解法, 挺好的

2023-09-06 04:52 UTC, RukiaOvO commented on work1/Bonus4.go
手写的qwq，专业名词不太懂，瞎扯了

2023-09-06 04:57 UTC, RukiaOvO commented on work1/Bonus2.md
已改qwq

2023-09-06 05:02 UTC, RukiaOvO commented
6.go这个文件名是Bonus1要求的qwq，我就照着题目要求做了

2023-09-06 08:19 UTC, ozline approved these changes

2023-09-07 02:30 UTC, jiuxia211 approved these changes
LGTM

2023-09-07 02:30 UTC, jiuxia211 commented on work1/P5737.go
虽然但是，为什么不用bool类型

2023-09-07 10:32 UTC, merged