102203103 - work1,2
west2-online-reserve/collection-golang pull request #2
Opened 2023-09-06 04:08 UTC by alittleswarm

work1：基本都写完了
work2：基础都写完了，Bonus只完成了教务处的第一个，第二个试着做了一下但是失败了,bili的都没完成

2023-09-06 04:24 UTC, ozline commented
说一下规范问题:

1. 第二个commit的第一个字母不应当大写
2. 还是第二个commit, 应该用fix而不是update, 比如fix: work2 xxx(这里改为你修复bug的内容, 不用很长)

下次提交commit注意一下就好了, 不用改

2023-09-06 04:30 UTC, ozline commented on work2/alittleswarm/2.go
字符串拼接部分, 你可以去了解一下正常拼接、Sprintf、StringBuilder、ByteBuffer、ByteContact之间的性能差异

网上有资料, 不过建议你自己写一个benchmark测一下, 你可以参考网上的代码跑一遍benchmark

2023-09-06 04:32 UTC, ozline commented on work2/alittleswarm/1.go
我关注到了你的保存文件是使用.txt而且是非常古老的拼接术

看到你的学号, 你这里需要改成使用mysql存储, 可以看一下gorm

2023-09-06 04:33 UTC, ozline commented on work2/alittleswarm/go.mod
module名字可以是很多, 但为什么是workspace...

go有一个go workspace的...下一轮作业记得换个module

2023-09-06 04:34 UTC, ozline requested changes, later dismissed
挺好的, 但是需要改点东西

2023-09-06 07:44 UTC, alittleswarm commented on work2/alittleswarm/go.mod
研究一下，module都用的稀里糊涂的

2023-09-06 16:17 UTC, jkskj reviewed
下次记得在得出结果后就可以return,别继续啦

2023-09-06 16:17 UTC, jkskj commented on work1/alittleswarm/4.go
flag为false后就可以直接return啦

2023-09-06 16:17 UTC, jkskj commented on work1/alittleswarm/b3.go
ok为true就可以return啦

2023-09-08 08:02 UTC, jkskj requested changes
边界判断注意一下

2023-09-08 08:02 UTC, jkskj commented on work1/alittleswarm/4.go
循环的判断语句有问题

2023-09-16 01:16 UTC, XZ0730 submitted a review, later dismissed

2023-09-16 01:16 UTC, XZ0730 commented on work1/alittleswarm/2.go
fmt.Printf

2023-09-16 05:15 UTC, jkskj reviewed
错误处理改一下

2023-09-16 05:15 UTC, jkskj commented on work2/alittleswarm/2.go
> +		}
错误处理加一下

2023-09-16 05:15 UTC, jkskj commented on work2/alittleswarm/2.go
err别用println输出，输出的是地址，没有err携带的信息，输出方面最好还是用 fmt 包

2023-09-17 09:55 UTC, XZ0730 submitted a review, later dismissed

2023-09-17 10:10 UTC, jkskj commented on work1/alittleswarm/4.go
> +	for i := 2; i < int(math.Sqrt(float64(x))); i++ {
边界判断怎么又改回去了呢(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )

2023-09-17 12:19 UTC, alittleswarm commented on work1/alittleswarm/4.go
> +	for i := 2; i < int(math.Sqrt(float64(x))); i++ {
可能不小心覆盖了(￣ω￣;)

2023-09-18 05:26 UTC, jkskj approved these changes

2023-09-29 13:13 UTC, XZ0730 approved these changes

2023-09-29 13:14 UTC, merged