add：complete work1
west2-online-reserve/collection-golang pull request #4
Opened 2023-09-06 07:22 UTC by jsbjkskbs

Task1:已完成1、2、3、4、5，分别对应文件./Task1/1.go;2.go;3.go;4.go;5.go
Bonus:已完成Task1之下的1、3、3，分别对应文件./Bonus/6.go ninenine.txt;8.go;9.go
Q1(Bonus 2.):
go中的数组与切片的区别相似于c++中数组与STL库内的vector的区别，简言之，①数组应当是定长的，而切片可以自由改变长度；②数组的长度不应当为0，而切片的长度可以为0；③数组的地址是固定的，而切片的地址会因为其元素的改变而改变；④go与c++不同，当数组作为参数传入某个函数时，在函数内，操作的数组是一个"副本"，改变数组内某个元素的值并不会影响原数组的元素(区别于c++的地址传入)。而当切片作为参数传入某个函数时，在函数内，操作的切片是本体，改变切片内的数据会影响原切片的数据(类似于c++的引用传入)⑤类似于c++的vector，切片也有容量(cap())和长度(len())，容量对应的物理空间才是实际占有的物理空间。
创建切片的方式(以下为举例):①var slice []data_type；② slice := make([]data_type,len,cap) <=> var slice = make([]data_type,len,cap)，也可以使用已存在的切片/数组：③ slice1 := array/slice2[beg:end] (范围为[beg,end))或 slice1 := array/slice2
创建map的方式(以下为举例):① map_a = make(map[keyType]valueType)
Q2(Bonus 3(1).):详见8.go
Q3(Bonus 3(2).):详见9.go

2023-09-07 03:10 UTC, jiuxia211 requested changes
8.go 需要改改,其他都不错

2023-09-07 03:10 UTC, jiuxia211 commented on work1/jsbjkskbs/Task1/2.go
使用cnt:=0是更与golang契合的初始化方式

2023-09-07 03:10 UTC, jiuxia211 commented on work1/jsbjkskbs/Task1/5.go
我有点不太能理解你为什么这么输出切片,可读性并不会很好

2023-09-07 03:10 UTC, jiuxia211 commented on work1/jsbjkskbs/Bonus/8.go
有问题，首先，在我的电脑上输出的序列全是0？你不应该开一个协程去生成随机序列，你对该序列所有的处理可能都在序列生成完成之前，那就没有任何意义了，我paste一下我的输出
期望和值:9
已生成序列:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[13,18]
Reason:seq[13]=9,seq[18]=0

还有一个，在golang中命名最好不要用_(下划线)，用驼峰即可

2023-09-07 05:09 UTC, jiuxia211 submitted a review, later dismissed
LGTM

2023-09-07 11:43 UTC, jkskj submitted a review, later dismissed
LGTM

2023-09-08 12:19 UTC, jsbjkskbs commented
第二轮：
### 爬取福大通知、文件系统
一、完成非并发、并发两个版本
二、
       Bonus1.个人感觉爬取速度会受网络限制影响、同时两版本的算法不同也会造成误差；不过在运行时，我发现并发爬取比非并发的日志输出快了5-10倍
       Bonus2.我尝试过很多次goquery的Find()函数，发现压根底筛不出来点击量，用Edge的开发者工具查看对应区块，发现_showDynClicks(clicktype, owner, clickid)这个函数，最后追溯到system/resource/code/news/click/dynclicks.jsp路径，以此可以获得点击量
       Bonus3.已完成(原生SQL，通过"database/sql"与"github.com/go-sql-driver/mysql")

### 爬取Bilibili视频评论
一、已完成(在插入数据库的时候，mySQL报告rpid重复，不知道是程序内有bug还是因为b站评论区新增评论)
二、
       Bonus1.不敢试，怕被ban(未完成)
       Bonus2.见bilibili_reply_graph.md(已完成，很乱)
       Bonus3.见bonus2q3.json(部分参数已解释)

2023-09-28 17:53 UTC, jsbjkskbs commented
第三轮：

使用Hertz框架、MySQL 大致完成基本要求

但部分非200的StatusCode返回需要更改

完成Bonus.1

2023-09-30 01:05 UTC, jiuxia211 approved these changes, later dismissed

2023-09-30 03:04 UTC, XZ0730 approved these changes, later dismissed

2023-09-30 07:38 UTC, jsbjkskbs commented
第三轮：

大致完成基本要求


完成Bonus.1.2.5

2023-10-06 15:41 UTC, ozline commented
吐槽一下，你把 README.md 删掉的话，你 pr 过来也会把主仓库的 README.md 删掉的

你或许需要去寻找一些方法（比如把 README.md 补上）来避免这样的问题，你能添加/修改/删除的只能是你自己的文件夹内的东西

2023-10-06 18:30 UTC, ozline commented
我再吐槽一下！你的 commit 规范！做的快的话就多注意一下细节吧

2023-11-08 17:03 UTC, jiuxia211 approved these changes

2023-11-08 17:21 UTC, jiuxia211 submitted a review, later dismissed

2023-11-08 17:21 UTC, jiuxia211 commented on work2/jsbjkskbs/bilibili_reply.go
你不觉得单个文件的代码太多了吗，比如对数据库的初始化、操作等可以单独开一个包

2023-11-08 17:21 UTC, jiuxia211 commented on work2/jsbjkskbs/bilibili_reply.go
对于b站评论的接口可以参考https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/list.md

2023-11-08 17:21 UTC, jiuxia211 commented on work2/jsbjkskbs/Test/README.md
我自己测试的时候是会被封禁的，你需要完整的爬完所有评论再对照评论是否一致

2023-11-08 17:21 UTC, jiuxia211 commented on work2/jsbjkskbs/bilibili_reply.go
可以了解一下waitGroup，也许可以简化你的协程设计

2023-12-09 03:04 UTC, ozline approved these changes, later dismissed

2023-12-09 03:04 UTC, ozline commented on work3/jsbjkskbs/repo.txt
1. 建议阅读一下结构，命名有点抽象，比如`midware`是什么东西？
2. 尝试使用一下 Hertz 的代码生成，比如用 Thrift/Protobuf 写好后用 cli 生成
3. 注释写的挺好的
4. initializ 内放 router 有点没看懂，但是我要说的是 router 有一个 group 功能。你的写法，一旦接口数上去了，就不太直观了
5. hertz 有 `hlog`，不建议使用 `log` 了
6. mysql 部分，不建议直接`github.com/go-sql-driver/mysql`了，尝试一下 ORM 框架，例如 gorm 吧
7. 返回的 json 可以封装到一个`pack`包里，增强代码复用性和可读性

其他看着还挺好的

2023-12-09 03:13 UTC, ozline approved these changes
这边先合并了

2023-12-09 03:13 UTC, merged