add: complete works1
west2-online-reserve/collection-golang pull request #8
Opened 2023-09-08 03:25 UTC by bubbbbbble

2023-09-08 08:20 UTC, jkskj requested changes
改，另外可以不用txt，用一下markdown

2023-09-08 08:20 UTC, jkskj commented on work1/bubbbbbble/AtCoder ARC017A.go
1不是质数吧，而且循环的判断条件有问题，fmt.Printf 用于格式化输出，非格式化最好别用，还有函数命名，注意一下规范

2023-09-08 08:20 UTC, jkskj commented on work1/bubbbbbble/luoguP5737.go
重复了，而且写错题了

2023-09-08 08:20 UTC, jkskj commented on work1/bubbbbbble/Bonus3.txt
注释呢

2023-09-08 08:20 UTC, jkskj commented on work1/bubbbbbble/slice.go
for i :=0;i<50 i++
？

2023-09-10 12:12 UTC, jkskj approved these changes, later dismissed

2023-09-30 01:04 UTC, jiuxia211 approved these changes, later dismissed
LGTM

2023-10-03 11:48 UTC, jkskj submitted a review, later dismissed
work2 b站的评论呢，还有你的commit为什么从 complete works1 直接到 complete work3，跳级了吗

2023-11-08 13:09 UTC, jiuxia211 submitted a review, later dismissed
逻辑没啥问题，但是规范要注意，第二轮的代码太不雅了！

2023-11-08 13:09 UTC, jiuxia211 commented on work2/bubbbbbble/bilibili/dao/db.go
缩进怎么感觉很挤？

2023-11-08 13:09 UTC, jiuxia211 commented on work2/bubbbbbble/bilibili/main.go
有一点疑惑，next这个参数是什么意思

2023-11-08 13:09 UTC, jiuxia211 commented on work2/bubbbbbble/bilibili/main.go
cookie这个变量应该不需要放在循环体内，并且对于数据的处理不够优雅，你可以创建一个pack包，写一个函数来包装model.StoredReply

2023-11-08 13:09 UTC, jiuxia211 commented on work2/bubbbbbble/bilibili/model/model.go
同样奇怪的缩进

2023-11-08 13:09 UTC, jiuxia211 commented on work2/bubbbbbble/fzuNews/1.go
我发现你的两个模块是完全分开的，没有必要！一个项目最好只有一个go.mod，数据库没有必要分开，而且为什么fzu的模块就没有dao文件夹了，规范要注意！！！！

2023-11-08 14:57 UTC, jkskj commented on work2/bubbbbbble/bilibili/dao/db.go
不建议使用gorm来建表

2023-12-09 03:05 UTC, ozline commented
第三轮代码迁到你自己的仓库哈。

2023-12-17 11:36 UTC, jiuxia211 commented
提醒一下，第三轮的代码迁移到你的自己的仓库，参考已经合并的pr

2023-12-18 17:21 UTC, closed without merging

2023-12-18 17:21 UTC, ozline commented
Due to your failure to modify the PR in a timely manner and your absence from the defense on the evening of December 18th, I have closed this PR. If you wish to continue participating in the assessment of the studio, please contact both me and the group owner of the communication group.

---
由于你没有在合适的时间修改好 pr，同时没有参与 12 月 18 日晚间的答辩，这个 pr 被我关闭了。如果需要继续参与工作室的考核，请你和交流群的群主取得联系